<?php 

$books = [[
            "name" => "Do Androids Dream of Electric Sheep",
            "author" => "Harold Klen",
            "purchaseUrl" => "http://example.com",
            "releaseYear" => 2014
          ],
          [
            "name" => "Atomic Habits",
            "author" => "Laracast",
            "purchaseUrl" => "http://example.com",
            "releaseYear" => 2019
           ]
        ];

$favoriteMovies = [
            [
                "name" => "Ruby Sparks",
                "releaseYear" => 2012
            ],
            [
                "name" => "Star Wars Episode I - The Phantom Menace",
                "releaseYear" => 1999
            ],
            [
                "name" => "About Time",
                "releaseYear" => 2013
            ],
            [
                "name" => "Some Movie",
                "releaseYear" => 1904
            ]
    ];

function filterMovieByYear($favoriteMovies) {
     $filteredMovies = [];

    foreach($favoriteMovies as $fave) {
        if ($fave["releaseYear"] >= 2000 ) {
            $filteredMovies[] = $fave; // append
        }   
    }
    return $filteredMovies;
}    

/*
 * The $movie variable in the arrow function (fn($movie) => ...) is automatically generated by 
 * array_filter. It represents each element (in this case, each movie) in the $favoriteMovies 
 * array as it iterates through the array. 
 * The arrow function is applied to each movie in the * array.
*/

$filterMovieByYearArrow = array_filter($favoriteMovies, fn($movie) => $movie['releaseYear'] > 1950 && $movie['releaseYear'] < 2020);

require "index.view.php";